<?php 
/**
 * Eggwhite_Upload extension
 *
 *
 * @category Eggwhite Cartupload
 * @package  Eggwhite_Upload
 * @author   D.V <Eggwhite Dev>
 */


if($block->isEnable()){
$collect = $block->getUploadCollection($block->getRealOrderId());
$url = $block->getUploadpath();
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Uploaded File Information') ?></span>
    </div>
<table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                 <th class="col-type"><span><?php echo __('File Type'); ?></span></th>
                 <th class="col-thumb"><span><?php echo __('Thumbnail'); ?></span></th>
                 <th class="col-price-original"><span><?php echo __('File Name'); ?></span></th>
		<th class="col-comment-original"><span><?php echo __('Comment'); ?></span></th>
            </tr>
        </thead>
        <tbody class="">
	<?php if(count($collect) < 1){ ?>
		<tr><td><?php echo __('No Record Found'); ?></td></tr>
	<?php } foreach($collect as $item) { ?>
		 <tr>
                   <td class="col-type">
			    <div class="order_item_title"><?php echo $item->getType(); ?></div>
		   </td>
                   <td class="col-thumb">
		   <?php $_ext = pathinfo($item->getFilename(), PATHINFO_EXTENSION);
			 if ($_ext == 'jpeg' || $_ext == 'jpg' || $_ext == 'png' || $_ext == 'ico' || $_ext == 'gif') { ?>
				<a target="_blank" href="<?php echo $url.$item->getFilename(); ?>"><img src="<?php echo $url.$item->getFilename(); ?>" height="40" width="45" /></a>
		   <?php } else { ?>
			        <a target="_blank"href="<?php echo $url.$item->getFilename(); ?>"><img src="<?php echo $url.'icons/'.$_ext.'.png'; ?>" height="40" width="45" /></a>
		   <?php } ?>
		   </td>
                   <td class="col-price-original"><a target="_blank" href="<?php echo $url.$item->getFilename(); ?>"><?php echo $item->getFilename(); ?></a></td>	
		    <td class="col-comment-original"><?php echo $item->getComments(); ?></td>
   		</tr> 
	<?php } ?>
      </tbody>
</table>
    <div>
    </div>
</section>
<?php } ?>
